---
kind: "operation"
client: "rug-cli 0.22.0"
generator:
  name: "NewRugArchiveProject"
  group: "atomist-rugs"
  artifact: "rug-archive"
  version: "0.11.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-archive.git"
    branch: "a881183f4382aa17443b589213889902d2ae69ac"
    sha: "a881183"
  parameters:
    - "group_id": "atomist-rugs"
    - "description": "Atomist Docker rug editors"
    - "project_name": "docker-editors"

---
kind: "operation"
client: "rug-cli 0.22.0"
editor:
  name: "EnableTravisForRugArchiveTS"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.12.2"
  origin:
    repo: "https://github.com/atomist-rugs/travis-editors.git"
    branch: "fb5fab9406ad30c0be90cb8272a8bb22fd8a3242"
    sha: "fb5fab9"
  parameters:
    - "repo_slug": "atomist-rugs/docker-editors"
    - "org": ".org"
    - "github_token": "4**************************************b"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t************h"
    - "maven_token": "A***********************************************************************i"

---
kind: "operation"
client: "rug-cli 0.22.0"
editor:
  name: "atomist-rugs.rug-editors.AddTypeScript"
  group: "atomist-rugs"
  artifact: "rug-editors"
  version: "0.6.0"
  origin:
    repo: "https://github.com/atomist-rugs/rug-editors.git"
    branch: "2c1257b26b749c24f3204b8484faa19b6df666c3"
    sha: "2c1257b*"

